### ISSUE TITLE
This plugin broke dokuwiki editor

### ISSUE THREAD

**Issue by ya-isakov** [cosmocode/recommend#1]
Hello! I install this plugin, but many toolbar buttons in dokuwiki editor doesn't work! (for example, "image", buttons for changing headings etc;come buttons insert 'undefined' in page). I disable all non-standard plugins and change template to 'default' - no result, buttons still doesn't works. Then I remove script.js from plugin directory and buttons begin to work.

**Comment by annda** [comment]
Javascript has been recently refactored in #7
