### ISSUE TITLE
Invalid sender email address submitted?

### ISSUE THREAD

**Issue by atlarep** [cosmocode/recommend#6]
When I click on 'Send Recommendation" I get this error. 

![image](https://cloud.githubusercontent.com/assets/20726009/18325598/f4801fc2-750f-11e6-85f4-9bd5942b4dd4.png)
I've tried 5 different e-mail addresses, but the error keeps showing.
Any ideas?

**Comment by atlarep** [comment]
Hello,
Any word on this?

**Comment by annda** [comment]
Closing because the report was made for an older version of the plugin.
